RentRoom/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentRoom.Classes;
using RentRoom.Context;
using RentRoom.Models;
using RentRoom.ViewModels;

namespace RentRoom.Controllers
{
    public class RentController : Controller
    {
         private readonly IdentityContext _context;
         public RentController(IdentityContext context)
         {
            _context = context;
         }
         public IActionResult Index()
         { 
         return View();
         }
         [HttpPost]
         public IActionResult RentRoomChangeWeek( string selecedWeek, string selecedRoom)
         {
             int temp = Int32.Parse(selecedWeek);
             DateTimeManage myDateTimeManage = new DateTimeManage();
             ComJson myData = new ComJson();
             string[] tempTeble = myDateTimeManage.FourWeeksTable(temp - 1);
             RoomDescriptionModel myRoomDescriptionModel = new RoomDescriptionModel();
             ConfigHour myConfigHour = new ConfigHour();
             if (!string.IsNullOrEmpty(selecedRoom))
             {
                 var myRoom = _context.RoomDescriptionModels.Where(x => x.NameOfRoom == selecedRoom)
                    .Select(i => i.Id).ToArray();
                 var myRents = _context.RoomRent.Where(x => x.RoomDescriptionModelId == myRoom[0]).ToList();
                 for (int i = 0; i < myRents.Count; i++)
                 {
                     string sTemp = myRents[i].DateOfEvent + " " + myRents[i].HourOfBeginEvent;
                     myData.ReservTerms.Add(sTemp);
                 }
             }
             for (int i = 0; i < 7; i++)
             {
                myData.dataTable[i] = tempTeble[i];
             }
             myData.HourPeriod = new []{ myConfigHour.GetStartHours(), myConfigHour.GetEndHours() };
             return Json(myData);
         }
         [HttpPost]
         public IActionResult RentRoomReservationTerms(string term, string room)
         {
            RoomRentModel myRentModel = new RoomRentModel();
            var myRoom = _context.RoomDescriptionModels.Where(x => x.NameOfRoom == room)
                .Select(i => i.Id).ToArray();
            string[] dateFromViev = term.Split();
            int temp = Int32.Parse(dateFromViev[1]);
            var temp2 = HttpContext.User.Identity.Name;
            var temp3 = _context.UserModels.Where(x => x.UserName == temp2)
                .Select(i => i.CustomersID).ToArray();
            var isItFree = _context.RoomRent.Where(x => x.DateOfEvent == dateFromViev[0])
                .Where(d => d.HourOfBeginEvent == dateFromViev[1]).ToList();
            if (isItFree.Count == 0)
            {
                temp = temp + 1;
                myRentModel.StateOfReservation = "New";
                myRentModel.DateOfEvent = dateFromViev[0];
                myRentModel.HourOfBeginEvent = dateFromViev[1];
                myRentModel.HourOfEndEvent = temp.ToString();
                myRentModel.CreatedByUser = HttpContext.User.Identity.Name;
                myRentModel.CreatedByChanel = "Internet";
                myRentModel.CreatedDate = DateTime.Now.ToString("d");
                myRentModel.NameOfEvent = "Cos Tam";
                myRentModel.CustomersId = temp3[0] ;
                myRentModel.RoomDescriptionModelId = myRoom[0];
                myRentModel.OwnerOfEvent = HttpContext.User.Identity.Name;
                _context.Add(myRentModel);
                try
                {
                    _context.SaveChanges();
                }
                catch (DbUpdateException)
                {
                     return Content("Brak dostepu do Bazy");
                }
            }
            else
            {

            }
         return RedirectToAction("Index", "Account");
         }
        [HttpPost]
        public IActionResult RentRoomTerm(string room)
        {
            ComJson myData = new ComJson();
            DateTimeManage myDateTimeManage = new DateTimeManage();
            string[] tempTeble = myDateTimeManage.FourWeeksTable(0);
            string temp = "";
            var myRents = new List<RoomRentModel>();
            ConfigHour myConfigHour = new ConfigHour();
            if (!string.IsNullOrEmpty(room))
            {
                var myRoom = _context.RoomDescriptionModels.Where(x => x.NameOfRoom == room)
                    .Select(i => i.Id).ToArray();
                 myRents = _context.RoomRent.Where(x => x.RoomDescriptionModelId == myRoom[0]).ToList();
                for (int i = 0 ; i < myRents.Count; i++)
                {
                    string sTemp = myRents[i].DateOfEvent + " " + myRents[i].HourOfBeginEvent;
                    myData.ReservTerms.Add(sTemp);
                }
            }
            for (int i = 0; i < 7; i++)
            {
                myData.dataTable[i] = tempTeble[i];
            }
            myData.HourPeriod = new[] { myConfigHour.GetStartHours(), myConfigHour.GetEndHours() };
            return Json(myData);
        }
        [HttpPost]
        public IActionResult RentRoomTermSelectListData()
        {
            var listFromDataBase = _context.RoomDescriptionModels.ToList();
            var listOfRooms = new List<string>();
            for (int i = 0; i < listFromDataBase.Count; i++)
            {
                string name = listFromDataBase[i].NameOfRoom;
                listOfRooms.Add(name);
            }
            return Json(listOfRooms);
        }
        public IActionResult ListRents()
        {
            List<ListRentsViewModel> listOfRends = new List<ListRentsViewModel>();
            var temp2 = HttpContext.User.Identity.Name;
            var temp3 = _context.UserModels.Where(x => x.UserName == temp2)
                .Select(i => i.CustomersID).ToArray();
            var myRents = _context.RoomRent.Where(x => x.CustomersId == temp3[0]).ToList();
            for (int i = 0; i < myRents.Count; i++)
            {
                ListRentsViewModel myListRents = new ListRentsViewModel();
                var tempNameOfRoom = _context.RoomDescriptionModels
                    .Single(x => x.Id == myRents[i].RoomDescriptionModelId);
                myListRents.NameOfRoom = tempNameOfRoom.NameOfRoom;
                myListRents.DateOfEvent = myRents[i].DateOfEvent;
                myListRents.HourEvent = myRents[i].HourOfBeginEvent;
                myListRents.Id = myRents[i].Id;
                listOfRends.Add(myListRents);
            }           
            return View(listOfRends);
        }
    }
}

RentRoom/Controllers/RoomDescriptionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentRoom.Context;
using RentRoom.Models;

namespace RentRoom.Controllers
{
    public class RoomDescriptionController : Controller
    {
        private readonly IdentityContext _context;

        public RoomDescriptionController(IdentityContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddRoom()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddRoom(RoomDescriptionModel roomDescription)
        {
            
            var listFromDataBase = _context.RoomDescriptionModels
                .Where(x => x.NameOfRoom == roomDescription.NameOfRoom)
                .ToList();

            //for (int i = 0; i < listFromDataBase.Count; i++)
            //{
            //    string name = listFromDataBase[i].NameOfRoom;
            //    if (name == roomDescription.NameOfRoom)
            //    {
            //        TempData["Massege"] = "Sala o podanej nazwie juz istneje";
            //        return AddRoom();
            //    }
             
            //}
            //if (listFromDataBase.Contains(name))
            //{

            //}

            //if (string.IsNullOrEmpty(roomDescription.NameOfRoom))
            //{
            //    return Content("Prosze podać nazwę sali");
            //}
            if (ModelState.IsValid)
            { 
            _context.Add(roomDescription);

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (roomDescription.Id != default(int))
                {
                    roomDescription.Id = default(int);
                    _context.SaveChanges();
                }
            }
            }
            return AddRoom();
        }
    }
}

RentRoom/Views/RoomDescription/AddRoom.cshtml
@model RentRoom.Models.RoomDescriptionModel
@TempData["Massege"]

@{
    ViewData["Title"] = "AddRoom";
}

<nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e3f2fd">
    @Html.ActionLink("Home", "Index", "Account")

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Rezerwacja Sali", "Index", "Rent")

                }
            </li>
            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Sale", "Index", "RoomDescription")

                }
            </li>
            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Nowa Sala", "AddRoom", "RoomDescription")

                }
            </li>


        </ul>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="nav-link active">
                @Html.ActionLink("Logout", "LogOut", "Account")
            </div>
        }
        
        @if (User.Identity.IsAuthenticated)
        {
            <div class="magin-right">Użytkownik Zalogowany.</div>
        }
        else
        {
            <div class="magin-right">Użytkownik Niezalogowany.</div>
        }

    </div>
</nav>

<h4>RoomDescriptionModel</h4>
<hr />

<form asp-action="AddRoom">
<div class="magin-left">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group col-md-6">
                <label asp-for="NameOfRoom"></label>
                <input asp-for="NameOfRoom" class="form-control" placeholder="Nazwa Sali" />
                <span asp-validation-for="NameOfRoom" class="text-danger"></span>
            </div>
        <div class="form-group col-md-6">
                <label asp-for="IsAvailable">Sala Dostepna</label>
                @Html.DropDownListFor(x => x.IsAvailable, new[] {
                    new SelectListItem() {Text = "Tak", Value = "Yes"},
                    new SelectListItem() {Text = "Nie", Value = "No"}
                }, "Wybierz opcje")
                <p></p>
                <span asp-validation-for="IsAvailable" class="text-danger"></span>
            </div>
            <div  class="form-group col-md-6">
                <label asp-for="SizeOfRoom" >Podaj rozmiar sali w m2.</label>
                <input asp-for="SizeOfRoom" class="form-control" placeholder="Rozmiar Sali" />
                <span asp-validation-for="SizeOfRoom" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="FeePerHour" type="number">Podaj Stawkę Wynajmu</label>
                <input asp-for="FeePerHour" class="form-control" placeholder="Rozmiar Sali" />
                <span asp-validation-for="FeePerHour" class="text-danger" type="number"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
       
    </div>
</div>

</form>

RentRoom/Views/RoomDescription/Index.cshtml
@model RentRoom.Models.RoomDescriptionModel

@{
    ViewData["Title"] = "Index";
}

<nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e3f2fd">
    @Html.ActionLink("Home", "Index", "Account")

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Rezerwacja Sali", "Index", "Rent")

                }
            </li>
            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Sale", "Index", "RoomDescription")

                }
            </li>
            <li class="nav-link active">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Nowa Sala", "AddRoom", "RoomDescription")

                }
            </li>


        </ul>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="nav-link active">
                @Html.ActionLink("Logout", "LogOut", "Account")
            </div>
        }
        
            @if (User.Identity.IsAuthenticated)
            {
                <div class="magin-right">Użytkownik Zalogowany.</div>
            }
            else
            {
                <div class="magin-right">Użytkownik Niezalogowany.</div>
            }

    </div>
</nav>